MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/home/zhenjie/pre_train_model/trans_pretrained/jx_vit_base_p16_224-80ecf9dd.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'vcnet'
  NO_MARGIN: True
  DEVICE_ID: ('1')
  TRANSFORMER_TYPE: 'resnet50'
  STRIDE_SIZE: [16, 16]
  DIST_TRAIN: False
  MQ: True
  # 消融
  SIE_CAMERA: False
  SIE_VIEW: False
  JPM: False

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
   NAMES: ('LCRI800')
   ROOT_DIR: ('/DATA/DATASETS')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 3
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 80
  BASE_LR: 0.008
  IMS_PER_BATCH: 60
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 80
  LOG_PERIOD: 100
  EVAL_PERIOD: 10
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  WEIGHT: '/home/zhenjie/VCNet_re/logs/lcri_vcnet_base/vcnet_stage2_80.pth'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: 'logs/lcri_vcnet_base_dcsp'